fix: include cosdec in ra tod
MUSTANG-SZ/WITCH pull request #68
Opened 2024-06-07 16:09 UTC by skhrg

2024-06-08 21:58 UTC, lucadimascolo requested changes
Everything looks fine, except for the (maybe) extra `[x,y]` term in `witch/utils.py` (line 282; see corresponding comment)

2024-06-08 21:58 UTC, lucadimascolo commented on witch/utils.py
> +    return tuple(jnp.meshgrid(x, y, z, sparse=True, indexing="ij") + [x0, y0])
Shouldn't this simply be 

```
return tuple(jnp.meshgrid(x, y, z, sparse=True, indexing="ij")
```
without the `+ [x0, y0])` term? We are already adding `x0` and `y0` to `x` and `y`, respectively (lines 277 and 279)

2024-06-09 05:07 UTC, skhrg commented on witch/utils.py
> +    return tuple(jnp.meshgrid(x, y, z, sparse=True, indexing="ij") + [x0, y0])
Thats appending them so the tuple is now `(x_grid, y_grid, z_grid, x0, y0)` so that we don't need to change to inputs to the modeling code for `transform_grid` to have them.

2024-06-09 10:00 UTC, lucadimascolo commented
Oh yes, I am dumb.Ok, I am going to accept the pull request as soon as I get home.On 9 Jun 2024, at 07:07, Saianeesh Keshav Haridas ***@***.***> wrote:﻿
@skhrg commented on this pull request.



In witch/utils.py:
>      z = jnp.linspace(-1 * r_map, r_map, 2 * int(r_map / dz))
 
-    return jnp.meshgrid(x, y, z, sparse=True, indexing="ij")
+    return tuple(jnp.meshgrid(x, y, z, sparse=True, indexing="ij") + [x0, y0])

Thats appending them so the tuple is now (x_grid, y_grid, z_grid, x0, y0) so that we don't need to change to inputs to the modeling code for transform_grid to have them.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-06-09 14:12 UTC, lucadimascolo approved these changes

2024-06-09 14:57 UTC, merged